---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-home-operations
spec:
  provider:
    onepasswordSDK:
      vault: Operations
      auth:
        serviceAccountSecretRef:
          name: onepassword-home-operations-secret
          namespace: external-secrets
          key: token
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-home-operations
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-home-operations
  target:
    name: onepassword-home-operations-secret
    template:
      data:
        token: "{{ .OP_SERVICE_ACCOUNT_TOKEN }}"
  dataFrom:
    - extract:
        key: 1password
