{
 "title": "Radarr",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(radarr_system_status, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "radarr_system_status{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "missing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_missing_total{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "in queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_queue_total{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "health issues",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_system_health_issues{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_total{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "wanted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "radarr_movie_wanted_total{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "d/l past month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(radarr_movie_downloaded_total{job=\"$instance\"}[30d]))"
    }
   ]
  },
  {
   "title": "monitored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_monitored_total{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_filesize_total{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "d/ past week",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(radarr_movie_downloaded_total{job=\"$instance\"}[7d]))"
    }
   ]
  },
  {
   "title": "qualities",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(radarr_movie_quality_total{job=\"$instance\"}) by (quality))",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "log",
   "type": "logs",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{k8s_container=\"radarr\"} | json | line_format \"{{.message}}\""
    }
   ]
  }
 ]
}