---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-unifi
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      external-dns-unifi:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          webhook:
            image:
              repository: ghcr.io/home-operations/external-dns-unifi-webhook
              tag: 0.10.10@sha256:9ff9e2a9ba4ab42026ae3b500524d26e6f8b47e7c84c3162121c15627d8dcb6b
            env:
              UNIFI_HOST: https://unifi.internal
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
            resources: &resources
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            restartPolicy: Always
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        containers:
          app:
            image:
              repository: registry.k8s.io/external-dns/external-dns
              tag: v0.22.0@sha256:5fdcaf7deb5c158f93a1fc6fe169cdff4cfb9ae0172bee1a90ab0ef74fb9c9cf
            args:
              - --domain-filter=k13.dev
              - --events
              - --interval=1m
              - --log-format=text
              - --log-level=info
              - --policy=sync
              - --provider=webhook
              - --registry=txt
              - --source=gateway-httproute
              - --source=service
              - --txt-owner-id=k8s
              - --txt-prefix=k8s.%{record_type}-
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 7979
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources: *resources
            securityContext: *securityContext
        serviceAccount:
          name: external-dns-unifi
    defaultPodOptions:
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
