---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      jellyfin:
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.6@sha256:25db4eb10143c1c12adb79ed978e31d94fc98dc499fbae2d38b2c935089ced3e
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  periodSeconds: 10
                  failureThreshold: 30
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
              limits:
                memory: 10Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: jellyfin
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      config-cache:
        existingClaim: "{{ .Release.Name }}-cache"
        globalMounts:
          - path: /config/cache
            subPath: cache
          - path: /config/metadata
            subPath: metadata
      media:
        type: nfs
        server: tank.internal
        path: /mnt/tank/media
        globalMounts:
          - readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /config/log
                subPath: log
              - path: /config/transcode
                subPath: transcode
              - path: /tmp
                subPath: tmp
    rawResources:
      gpu:
        apiVersion: resource.k8s.io/v1
        kind: ResourceClaimTemplate
        spec:
          spec:
            spec:
              devices:
                requests:
                  - name: gpu
                    exactly:
                      deviceClassName: gpu.amd.com
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            url: https://{{ .Release.Name }}.k13.dev/health
        hostnames:
          - "{{ .Release.Name }}.k13.dev"
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    service:
      app:
        ports:
          http:
            port: *port
