---
rules:
  - seriesQuery: probe_success{instance=~".+:2049"}
    resources:
      template: <<.Resource>>
    name:
      matches: ""
      as: nfs_probe_success
    metricsQuery: max_over_time(probe_success{instance=~".+:2049"}[1m])
