---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - m0-kvm.internal
        - m1-kvm.internal
        - m2-kvm.internal
        - tank.internal
        - tank-ipmi.internal
        - unifi.internal
        - ups.internal
