{
 "title": "Synology SNMP DashBoard",
 "description": "A Dashboard for Synology NAS based on SNMP and Prometheus",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": {
     "query": "query_result(ssCpuUser{job=\"snmp-exporter-synology-nas\"})"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(ifName{job=\"snmp-exporter-synology-nas\",instance=\"$Device\"})"
    }
   },
   {
    "name": "raidName",
    "label": "Volume ID",
    "query": {
     "query": "query_result(raidName{job=\"snmp-exporter-synology-nas\",instance=\"$Device\"})"
    }
   },
   {
    "name": "storageIODevice",
    "label": "Disk",
    "query": {
     "query": "query_result(storageIODevice{job=\"snmp-exporter-synology-nas\",instance=\"$Device\"})"
    }
   },
   {
    "name": "spaceIODevice",
    "label": "Volume Name",
    "query": {
     "query": "query_result(spaceIODevice{job=\"snmp-exporter-synology-nas\",instance=\"$Device\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sysUpTime{instance='$Device',job=\"snmp-exporter-synology-nas\"}/100",
     "legendFormat": "uptime"
    },
    {
     "expr": "upgradeAvailable{instance='$Device',job=\"snmp-exporter-synology-nas\"}"
    },
    {
     "expr": "temperature{job=\"snmp-exporter-synology-nas\", instance='$Device'}"
    },
    {
     "expr": "cpuFanStatus{job=\"snmp-exporter-synology-nas\",instance='$Device'}"
    },
    {
     "expr": "systemFanStatus{job=\"snmp-exporter-synology-nas\",instance='$Device'}"
    },
    {
     "expr": "systemStatus{job=\"snmp-exporter-synology-nas\",instance='$Device'}"
    },
    {
     "expr": "powerStatus{job=\"snmp-exporter-synology-nas\",instance='$Device'}"
    }
   ]
  },
  {
   "title": "System State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ssCpuUser{job=\"snmp-exporter-synology-nas\", instance='$Device'} + ssCpuSystem{job=\"snmp-exporter-synology-nas\", instance='$Device'}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "laLoadInt{job=\"snmp-exporter-synology-nas\",instance='$Device'}",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ssCpuSystem{instance='$Device',job='snmp-exporter-synology-nas'}",
     "legendFormat": "System"
    },
    {
     "expr": "ssCpuUser{instance='$Device',job='snmp-exporter-synology-nas'}",
     "legendFormat": "User"
    },
    {
     "expr": "ssCpuIdle{instance='$Device',job='snmp-exporter-synology-nas'}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "serviceUsers{instance='$Device',job=\"snmp-exporter-synology-nas\"}"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(memTotalReal{job=\"snmp-exporter-synology-nas\", instance='$Device'} - (memAvailReal{job=\"snmp-exporter-synology-nas\", instance='$Device'} + memCached{job=\"snmp-exporter-synology-nas\", instance='$Device'} + memBuffer{job=\"snmp-exporter-synology-nas\", instance='$Device'})) / memTotalReal{job=\"snmp-exporter-synology-nas\", instance='$Device'}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "memTotalReal{instance='$Device',job=\"snmp-exporter-synology-nas\"} + memTotalSwap{instance='$Device',job=\"snmp-exporter-synology-nas\"} - memTotalFree{instance='$Device',job=\"snmp-exporter-synology-nas\"}",
     "legendFormat": "Used Virtual Memory"
    },
    {
     "expr": "memTotalFree{instance='$Device',job=\"snmp-exporter-synology-nas\"}",
     "legendFormat": "Free Virtual Memory"
    },
    {
     "expr": "memTotalReal{instance='$Device',job=\"snmp-exporter-synology-nas\"} + memTotalSwap{instance='$Device',job=\"snmp-exporter-synology-nas\"}",
     "legendFormat": "Total Virtual Memory"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "memTotalReal{instance='$Device',job=\"snmp-exporter-synology-nas\"} - (memShared{instance='$Device',job=\"snmp-exporter-synology-nas\"} + memCached{instance='$Device',job=\"snmp-exporter-synology-nas\"} + memBuffer{instance='$Device',job=\"snmp-exporter-synology-nas\"} + memAvailReal{instance='$Device',job=\"snmp-exporter-synology-nas\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "memAvailReal{instance='$Device',job=\"snmp-exporter-synology-nas\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "memBuffer{instance='$Device',job=\"snmp-exporter-synology-nas\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "memCached{instance='$Device',job=\"snmp-exporter-synology-nas\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "memShared{instance='$Device',job=\"snmp-exporter-synology-nas\"}",
     "legendFormat": "Shared"
    },
    {
     "expr": "memTotalReal{instance='$Device',job=\"snmp-exporter-synology-nas\"} ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "memTotalSwap{instance='$Device',job=\"snmp-exporter-synology-nas\"} - memAvailSwap{instance='$Device',job=\"snmp-exporter-synology-nas\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "memAvailSwap{instance='$Device',job=\"snmp-exporter-synology-nas\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "memTotalSwap{instance='$Device',job=\"snmp-exporter-synology-nas\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ifPhysAddress{instance='$Device',job=\"snmp-exporter-synology-nas\"}"
    },
    {
     "expr": "ifAdminStatus{instance='$Device',job=\"snmp-exporter-synology-nas\"}"
    },
    {
     "expr": "ifConnectorPresent{instance='$Device',job=\"snmp-exporter-synology-nas\"}"
    },
    {
     "expr": "ifSpeed{instance='$Device',job=\"snmp-exporter-synology-nas\"}"
    },
    {
     "expr": "ifOperStatus{instance='$Device',job=\"snmp-exporter-synology-nas\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "diskTemperature{job=\"snmp-exporter-synology-nas\", instance='$Device'}"
    },
    {
     "expr": "diskType{job=\"snmp-exporter-synology-nas\", instance='$Device'}"
    },
    {
     "expr": "diskStatus{job=\"snmp-exporter-synology-nas\", instance='$Device'}"
    },
    {
     "expr": "diskModel{job=\"snmp-exporter-synology-nas\", instance='$Device'}"
    }
   ]
  },
  {
   "title": "Volume $raidName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "raidName",
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidStatus{job=\"snmp-exporter-synology-nas\",instance='$Device',raidName='$raidName'}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "raidTotalSize{instance='$Device',job=\"snmp-exporter-synology-nas\",raidName=~'$raidName'}",
     "legendFormat": "Total Size"
    },
    {
     "expr": "raidFreeSize{instance='$Device',job=\"snmp-exporter-synology-nas\",raidName=~'$raidName'}",
     "legendFormat": "Free Size"
    }
   ]
  },
  {
   "title": "Volume $spaceIODevice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "spaceIODevice",
   "targets": [
    {}
   ]
  },
  {
   "title": "Volume Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(spaceIONReadX{instance='$Device',job=\"snmp-exporter-synology-nas\",spaceIODevice=~\"$spaceIODevice\"}[$__interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(spaceIONWrittenX{instance='$Device',job=\"snmp-exporter-synology-nas\",spaceIODevice=~\"$spaceIODevice\"}[$__interval])",
     "legendFormat": "Written Bytes"
    }
   ]
  },
  {
   "title": "Volume IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(spaceIOReads{instance='$Device',job=\"snmp-exporter-synology-nas\",spaceIODevice=~\"$spaceIODevice\"}[$__interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(spaceIOWrites{instance='$Device',job=\"snmp-exporter-synology-nas\",spaceIODevice=~\"$spaceIODevice\"}[$__interval])",
     "legendFormat": "Written Bytes"
    }
   ]
  },
  {
   "title": "Device $storageIODevice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "storageIODevice",
   "targets": [
    {}
   ]
  },
  {
   "title": "Device Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(storageIONReadX{instance='$Device',job=\"snmp-exporter-synology-nas\",storageIODevice=~'$storageIODevice'}[$__interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(storageIONWrittenX{instance='$Device',job=\"snmp-exporter-synology-nas\",storageIODevice=~'$storageIODevice'}[$__interval])",
     "legendFormat": "Written Bytes"
    }
   ]
  },
  {
   "title": "Device IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(storageIOReads{instance='$Device',job=\"snmp-exporter-synology-nas\",storageIODevice=~'$storageIODevice'}[$__interval])",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "irate(storageIOWrites{instance='$Device',job=\"snmp-exporter-synology-nas\",storageIODevice=~'$storageIODevice'}[$__interval])",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  {
   "title": "Networking ($Interface)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "repeat": "Interface",
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifHCInOctets{job='snmp-exporter-synology-nas',instance='$Device',ifName=~'$Interface'}[$__interval]) or rate(ifInOctets{job='snmp',instance='$Device',ifName=~'$Interface'}[$__interval]) ",
     "legendFormat": "$Interface In"
    },
    {
     "expr": "rate(ifHCOutOctets{job='snmp-exporter-synology-nas',instance='$Device',ifName=~'$Interface'}[$__interval]) or rate(ifOutOctets{job='snmp',instance='$Device',ifName=~'$Interface'}[$__interval]) ",
     "legendFormat": "$Interface Out"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifInDiscards{job='snmp-exporter-synology-nas',instance='$Device',ifName=~'$Interface'}[$__interval])",
     "legendFormat": "Discards In"
    },
    {
     "expr": "rate(ifInErrors{job='snmp-exporter-synology-nas',instance='$Device',ifName=~'$Interface'}[$__interval])",
     "legendFormat": "Errors In"
    },
    {
     "expr": "rate(ifOutDiscards{job='snmp-exporter-synology-nas',instance='$Device',ifName=~'$Interface'}[$__interval])",
     "legendFormat": "Discards Out"
    },
    {
     "expr": "rate(ifOutErrors{job='snmp-exporter-synology-nas',instance='$Device',ifName=~'$Interface'}[$__interval])",
     "legendFormat": "Errors Out"
    }
   ]
  }
 ]
}