---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thelounge
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      thelounge:
        containers:
          app:
            image:
              repository: ghcr.io/thelounge/thelounge
              tag: 4.5.0@sha256:77fc1e6fa240e3867221682a47f27f772ac82a57b83a377c63e313f8eb7fd975
            env:
              THELOUNGE_HOME: /config/thelounge
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.k13.dev"
        parentRefs:
          - name: envoy-internal
            namespace: networking
    service:
      app:
        ports:
          http:
            port: 9000
