---
connectivity:
  checker:
    interval: 1m
    target: 1.1.1.1:53

endpoints:
  - conditions:
      - "[CONNECTED] == true"
    group: connectivity
    interval: 1m
    name: Cloudflare
    url: icmp://1.1.1.1

  - conditions:
      - "[CONNECTED] == true"
    group: connectivity
    interval: 1m
    name: Google
    url: icmp://8.8.8.8

  - conditions:
      - "[CONNECTED] == true"
    group: connectivity
    interval: 1m
    name: Quad9
    url: icmp://9.9.9.9

metrics: true

storage:
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db
  type: sqlite

ui:
  buttons:
    - name: Github
      link: https://github.com/buroa
    - name: Homelab
      link: https://github.com/buroa/k8s-gitops
  default-sort-by: group
  header: Status
  link: https://github.com/buroa
  logo: https://avatars.githubusercontent.com/u/36205263
  title: Status | Gatus

web:
  port: ${GATUS_WEB_PORT}
