---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
components:
  - ../../components/alerts
  - ../../components/namespace
  - ../../components/networking
resources:
  - ./flux-instance/ks.yaml
  - ./flux-operator/ks.yaml
