{
 "title": "SABnzbd",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Queue Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sabnzbd_queue_size" }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sabnzbd_queue_total_size_bytes", "legendFormat": "queue total" },
    { "expr": "sabnzbd_queue_remaining_bytes", "legendFormat": "queue remaining" }
   ]
  },
  {
   "title": "Download Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sabnzbd_queue_download_rate_bytes_per_second",
     "legendFormat": "download rate"
    }
   ]
  },
  {
   "title": "Server Total Download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sabnzbd_server_download_bytes{period=\"total\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Server Daily Download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sabnzbd_server_download_bytes{period=\"day\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Server Weekly Download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sabnzbd_server_download_bytes{period=\"week\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Server Monthly Download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sabnzbd_server_download_bytes{period=\"month\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{k8s_container=\"sabnzbd\"} | json | line_format \"{{.message}}\""
    }
   ]
  }
 ]
}