---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  repository:
    kind: ClusterRepository
    name: nas
  credentialProjection:
    enabled: true
  sources:
    - pvc:
        name: ${APP}
  copyMethod: Snapshot
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-block}
  retention:
    keepDaily: 7
    keepWeekly: 4
  verification:
    quick:
      cron: 0 5 * * *
      jitter: 2m
    deep:
      schedule:
        cron: 0 5 * * 0
        jitter: 1h
      capacity: 1Mi # Ignored
      storageClassName: openebs-hostpath
    successExpr: stats.files > 0 && stats.errors == 0
    verifyFilesPercent: 10
