---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  copyMethod: Snapshot
  credentialProjection:
    enabled: true
  repository:
    kind: ClusterRepository
    name: nas
  retention:
    keepDaily: 7
    keepHourly: 24
  sources:
    - pvc:
        name: ${APP}
  verification:
    deep:
      schedule:
        cron: H 5 1 * * # First of the month at 5am
        jitter: 1h
        timezone: America/Chicago
    quick:
      cron: H 3 * * * # Every day at 3am
      jitter: 1h
      timezone: America/Chicago
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-block}
