---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: downflate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: downflate-secret
    template:
      data:
        DOWNFLATE_WEBHOOK_SECRET: "{{ .DOWNFLATE_WEBHOOK_SECRET }}"
        DOWNFLATE_GITHUB_APP_CLIENT_ID: "{{ .GITHUB_APP_CLIENT_ID }}"
        DOWNFLATE_GITHUB_APP_PRIVATE_KEY: "{{ .GITHUB_APP_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: downflate
    - extract:
        key: github
