---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Image Pull

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  filter:
    name: Image Pull - Filter
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get Changed Files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        with:
          patterns: kubernetes/**/*

  flate:
    if: ${{ needs.filter.outputs.changed-files != '[]' }}
    needs: filter
    name: Image Pull - Flate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      images: ${{ steps.flate.outputs.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Flate
        uses: home-operations/flate/action@46bd035df3d0eba88e334567ebb76318ff6be1d7 # 0.1.35
        with:
          cache: true

      - name: Run Flate
        id: flate
        env:
          FLATE_OUTPUT: json
          FLATE_PATH: ./kubernetes/flux/cluster
        run: |
          echo 'images<<EOF' >> $GITHUB_OUTPUT
          flate diff images >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  pull:
    if: ${{ needs.flate.outputs.images != '[]' }}
    needs: flate
    name: Image Pull - Pull Images
    runs-on: k8s-gitops-runner
    strategy:
      matrix:
        image: ${{ fromJSON(needs.flate.outputs.images) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Install talosctl
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          cache: false
          tool_versions: |
            aqua:siderolabs/talos latest

      - name: Pull Image
        run: talosctl --nodes $NODE image pull ${{ matrix.image }}

  success:
    if: ${{ !cancelled() }}
    needs: [flate, pull]
    name: Image Pull - Success
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
